//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigFactory.Avalonia.Demo.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConfigFactory.Avalonia.Demo.Assets.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Bool Field.
        /// </summary>
        public static string Bool_Field {
            get {
                return ResourceManager.GetString("Bool Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Browser Field.
        /// </summary>
        public static string Browser_Field {
            get {
                return ResourceManager.GetString("Browser Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Dropdown Field.
        /// </summary>
        public static string Dropdown_Field {
            get {
                return ResourceManager.GetString("Dropdown Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Other Field.
        /// </summary>
        public static string Enum_Field {
            get {
                return ResourceManager.GetString("Enum Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended (probably redundant) description of Some Field, a text-based configuration.
        /// </summary>
        public static string Example_Description {
            get {
                return ResourceManager.GetString("Example Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Common.
        /// </summary>
        public static string Less_Common {
            get {
                return ResourceManager.GetString("Less Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Enum Field.
        /// </summary>
        public static string Other_Field {
            get {
                return ResourceManager.GetString("Other Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Text Field.
        /// </summary>
        public static string Text_Field {
            get {
                return ResourceManager.GetString("Text Field", resourceCulture);
            }
        }
    }
}
