name: Deploy

on:
  push:
    tags:
      - "v*"

env:
  nuget: "https://api.nuget.org/v3/index.json"
  authors: ArchLeaders
  description: |-
    Generic library for creating extensible config arrangements to be used with a UI builder
  readme: ./Readme.md
  repo: https://github.com/ArchLeaders/ConfigFactory
  spdx: AGPL-3.0-or-later
  tags: configuration;settings;avaloniaui;factory

jobs:
  deploy:
    name: Deploy ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: ConfigFactory
          - name: ConfigFactory.Core
          - name: ConfigFactory.Avalonia

    env:
      csproj: src/${{ matrix.config.name }}/${{ matrix.config.name }}.csproj
      bin: src/${{ matrix.config.name }}/bin

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install DotNET"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: "Restore packages"
        run: dotnet restore ${{ env.csproj }}

      - name: "Build project"
        shell: bash
        run: |
          dotnet build ${{ env.csproj }} \
          -c Release \
          --no-restore

      - name: "Get Version"
        id: version
        uses: battila7/get-version-action@v2

      - name: "Pack project"
        shell: bash
        run: |
          dotnet pack ${{ env.csproj }} \
          --no-restore \
          -c Release \
          -o ${{ env.bin }} \
          -p:Authors="${{ env.authors }}" \
          -p:Description="${{ env.description }}" \
          -p:PackageLicenseExpression="${{ env.spdx }}" \
          -p:PackageProjectUrl="${{ env.repo }}" \
          -p:PackageReadmeFile="${{ env.readme }}" \
          -p:PackageTags='"${{ env.tags }}"' \
          -p:PackageVersion="${{ steps.version.outputs.version-without-v }}" \
          -p:RepositoryUrl="${{ env.repo }}" \

      - name: "Push package"
        shell: bash
        run: |
          dotnet nuget push ${{ env.bin }}/*.nupkg \
          -k ${{ secrets.nuget_auth }} \
          -s ${{ env.nuget }}
